# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: violet

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Paro Engineering & University of Amsterdam'
    description: 'Alex Gabel — AI engineer at Paro Engineering and PhD researcher in Deep Learning at the University of Amsterdam.'
    twitter: 'gabel_alex'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Alex Gabel'
      # filename: 'logo.svg'
    highlight_active_link: true
    show_translations: true
    hide_language_name: false

# Site footer
footer:
  copyright:
    notice: '© {year} Alex Gabel. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
